version: 2.1
workflows:
  due_push_or_pull_request: #workflow名
    jobs:
      - checkoutFile
      - test:
          requires:
            - checkoutFile
      - sonarqube:
          requires:
            - checkoutFile
jobs:
  checkoutFile:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/workspace
    steps:
      - checkout
      - persist_to_workspace:
          root: . # workspaceのrootパス（絶対パスかworking_directoryからの相対パス）
          paths:
            - . # 共有するパス（絶対パスかrootからの相対パス）
  test:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/openjdk-15-boot-2.8.3-buster
    working_directory: ~/workspace
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run: sudo chmod +x ./gradlew
      - run: ./gradlew test
  sonarqube:
    docker: # https://circleci.com/docs/ja/2.0/docker-image-tags.json
      - image: circleci/openjdk-15-boot-2.8.3-buster
    working_directory: ~/workspace
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run: sudo chmod +x ./gradlew
      - run:
          name: sonarqube
          command: |
            ./gradlew sonarqube

