version: 2.1
workflows:
  due_push_or_pull_request: #workflow名
    jobs:
      - test
jobs:
  test:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    working_directory: ~/workspace
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run: sudo chmod +x ./gradlew
      - run: ./gradlew test
